// Generated by ResEdit 1.6.2
// Copyright (C) 2006-2014
// http://www.resedit.net

#include <windows.h>
#include <commctrl.h>
#include <richedit.h>
#include "resource.h"





//
// Bitmap resources
//
//LANGUAGE LANG_NEUTRAL, SUBLANG_NEUTRAL
1        BITMAP         "Strzalka.bmp"
2        BITMAP         "Checkbox1.bmp"
3        BITMAP         "Checkbox2.bmp"
4        BITMAP         "jaebe.bmp"
IDI_APP     ICON       "ikona.ico"